# -*- coding: utf-8 -*-
import math
import os
import sys
import datetime
import time

import cv2
import numpy as np

import Colordetect

# Form implementation generated from reading ui file 'multi_camera.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
sys.path.append("IMV/MVSDK")
from IMVApi import *
from functools import partial

sys.path.append("../")
import MVCdetect
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt, QThread, pyqtSignal, QMutex, QWaitCondition, QObject, QEvent
from PyQt5.QtGui import QPixmap
from PyQt5.QtWidgets import QMessageBox, QSizePolicy
from utils.myutil import file_is_pic, Globals
from MVCdetect import displayDeviceInfo

import checkdetect
import threading
import haikangdetect
import haikangMVCdetect
import export_pdf
from REF2XYZ import REF2XYZ
from XYZ2Lab import XYZ2LABCH

global i


class my_Qlabel(QtWidgets.QLabel):
    sinh = QtCore.pyqtSignal(int)
    sinw = QtCore.pyqtSignal(int)

    def __init__(self, widget):
        super(my_Qlabel, self).__init__()
        self.flag = True

    def mouseDoubleClickEvent(self, event):
        self.w = self.width()  # 获得label自身的宽高
        self.h = self.height()
        if self.flag:
            print(1)
            self.setWindowFlags(QtCore.Qt.Window)  # 使得label位于最高级别的窗口
            self.showFullScreen()  # 全屏显示
            self.flag = False
        else:
            print(2)
            self.setWindowFlags(QtCore.Qt.SubWindow)  # 使得label回到子窗口级别
            self.resize(self.w, self.h)  # 使得label宽高恢复原样
            self.showNormal()  # 恢复label原本大小
            self.flag = True

class cameraUI(QtWidgets.QMainWindow):

    def __init__(self, parent=None):
        super(cameraUI, self).__init__(parent)
        self.timer_detect = QtCore.QTimer()
        self.setupUi(self)
        self.init_logo()  # 初始化logo
        self.init_slots()  # 初始化槽函数
        self.file_path = None  # 数据路径
        self.model_path = None  # 模型路径
        self.file_suffix = None  # 文件后缀
        self.result_path = "result"  # 检测图片保存路径
        self.init_file()  # 初始化必要的文件夹
        self.mutex = QMutex()
        self.cond = QWaitCondition()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName("gridLayout")

        self.gridLayout_button = QtWidgets.QGridLayout()
        self.gridLayout_button.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_button.setSpacing(4)
        self.gridLayout_button.setObjectName("gridLayout_button")

        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        font_color = QtGui.QFont('Black', 35, 100)
        font_color.setBold(True)
        font_color.setWeight(QtGui.QFont.Weight.ExtraBold)
        font_color.setFamily("Black")
        # self.label_layout5 = QtWidgets.QLabel(self.centralwidget)
        # self.label_layout5.setStyleSheet("background-color: black;border: 1px solid black;")
        # self.label_layout5.setText("no camera")
        # self.label_layout5.setObjectName("label_layout5")
        # self.gridLayout.addWidget(self.label_layout5, 1, 2, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton_start.setMaximumSize(QtCore.QSize(300, 40))
        self.pushButton_start.setObjectName("pushButton_start")
        self.gridLayout_button.addWidget(self.pushButton_start, 0, 0, 1, 1)
        self.pushButton_model = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_model.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton_model.setMaximumSize(QtCore.QSize(300, 40))
        self.pushButton_model.setObjectName("pushButton_model")
        self.gridLayout_button.addWidget(self.pushButton_model, 1, 0, 1, 1)

        self.pushButton_file = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_file.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton_file.setMaximumSize(QtCore.QSize(300, 40))
        self.pushButton_file.setObjectName("pushButton_file")
        self.gridLayout_button.addWidget(self.pushButton_file, 0, 1, 1, 1)

        self.pushButton_show = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_show.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton_show.setMaximumSize(QtCore.QSize(300, 40))
        self.pushButton_show.setObjectName("pushButton_file")
        self.gridLayout_button.addWidget(self.pushButton_show, 1, 1, 1, 1)

        self.layout_color = QtWidgets.QLabel(self.centralwidget)
        self.layout_color.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.layout_color.setObjectName("layout_color")
        self.gridLayout_button.addWidget(self.layout_color, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_button)

        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setVerticalSpacing(19)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_camera1 = QtWidgets.QLabel(self.centralwidget)
        self.label_camera1.setObjectName("label_camera1")
        self.gridLayout_2.addWidget(self.label_camera1, 0, 0, 1, 1)
        self.label_status1 = QtWidgets.QLabel(self.centralwidget)
        self.label_status1.setText("")
        self.label_status1.setObjectName("label_status1")
        self.gridLayout_2.addWidget(self.label_status1, 0, 1, 1, 1)
        self.label_camera2 = QtWidgets.QLabel(self.centralwidget)
        self.label_camera2.setObjectName("label_camera2")
        self.gridLayout_2.addWidget(self.label_camera2, 1, 0, 1, 1)
        self.label_status2 = QtWidgets.QLabel(self.centralwidget)
        self.label_status2.setText("")
        self.label_status2.setObjectName("label_status2")
        self.gridLayout_2.addWidget(self.label_status2, 1, 1, 1, 1)
        self.label_camera3 = QtWidgets.QLabel(self.centralwidget)
        self.label_camera3.setObjectName("label_camera3")
        self.gridLayout_2.addWidget(self.label_camera3, 2, 0, 1, 1)
        self.label_status3 = QtWidgets.QLabel(self.centralwidget)
        self.label_status3.setText("")
        self.label_status3.setObjectName("label_status3")
        self.gridLayout_2.addWidget(self.label_status3, 2, 1, 1, 1)
        self.label_camera4 = QtWidgets.QLabel(self.centralwidget)
        self.label_camera4.setObjectName("label_camera4")
        self.gridLayout_2.addWidget(self.label_camera4, 3, 0, 1, 1)
        self.label_status4 = QtWidgets.QLabel(self.centralwidget)
        self.label_status4.setText("")
        self.label_status4.setObjectName("label_status4")
        self.gridLayout_2.addWidget(self.label_status4, 3, 1, 1, 1)
        self.label_camera5 = QtWidgets.QLabel(self.centralwidget)
        self.label_camera5.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_camera5.setObjectName("label_camera5")
        self.gridLayout_2.addWidget(self.label_camera5, 4, 0, 1, 1)
        self.label_status5 = QtWidgets.QLabel(self.centralwidget)
        self.label_status5.setText("")
        self.label_status5.setObjectName("label_status5")
        self.gridLayout_2.addWidget(self.label_status5, 4, 1, 1, 1)

        self.label_location1 = QtWidgets.QLabel(self.centralwidget)
        self.label_location1.setText("")
        self.label_location1.setObjectName("label_location1")
        self.gridLayout_2.addWidget(self.label_location1, 0, 2, 1, 1)
        self.label_location2 = QtWidgets.QLabel(self.centralwidget)
        self.label_location2.setText("")
        self.label_location2.setObjectName("label_location1")
        self.gridLayout_2.addWidget(self.label_location2, 1, 2, 1, 1)
        self.label_location3 = QtWidgets.QLabel(self.centralwidget)
        self.label_location3.setText("")
        self.label_location3.setObjectName("label_location1")
        self.gridLayout_2.addWidget(self.label_location3, 2, 2, 1, 1)
        self.label_location4 = QtWidgets.QLabel(self.centralwidget)
        self.label_location4.setText("")
        self.label_location4.setObjectName("label_location1")
        self.gridLayout_2.addWidget(self.label_location4, 3, 2, 1, 1)
        self.label_location5 = QtWidgets.QLabel(self.centralwidget)
        self.label_location5.setText("")
        self.label_location5.setObjectName("label_location1")
        self.gridLayout_2.addWidget(self.label_location5, 4, 2, 1, 1)
        # self.label_statusc = QtWidgets.QLabel(self.centralwidget)
        # self.label_statusc.setText("色度检查结果:")
        # self.label_statusc.setObjectName("label_statusc")
        # self.gridLayout_2.addWidget(self.label_statusc, 5, 0, 1, 2)

        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.label_layout2 = my_Qlabel(self.centralwidget)
        self.label_layout2.setStyleSheet("background-color: black;border: 1px solid black;")
        self.label_layout2.setText("no camera")
        self.label_layout2.setObjectName("label_layout2")
        self.gridLayout.addWidget(self.label_layout2, 1, 0, 1, 1)
        self.label_layout1 = my_Qlabel(self.centralwidget)
        self.label_layout1.setStyleSheet("background-color: black;border: 1px solid black;")
        self.label_layout1.setText("no camera")
        self.label_layout1.setObjectName("label_layout1")
        self.label_layout1.setScaledContents(True)
        self.gridLayout.addWidget(self.label_layout1, 0, 1, 1, 1)
        self.label_layout3 = my_Qlabel(self.centralwidget)
        self.label_layout3.setStyleSheet("background-color: black;border: 1px solid black;")
        self.label_layout3.setText("no camera")
        self.label_layout3.setObjectName("label_layout3")
        self.gridLayout.addWidget(self.label_layout3, 1, 1, 1, 1)
        # self.label_layout4 = QtWidgets.QLabel(self.centralwidget)
        # self.label_layout4.setStyleSheet("background-color: black;border: 1px solid black;")
        # self.label_layout4.setText("no camera")
        # self.label_layout4.setObjectName("label_layout4")
        # self.gridLayout.addWidget(self.label_layout4, 1, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 746, 22))
        self.menubar.setObjectName("menubar")
        self.func = self.menubar.addMenu("功能")
        # 给菜单项目添加子菜单
        self.check = self.func.addAction("外观检查")
        self.color = self.func.addAction("色度检查")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.label_camera1.setFont(font)
        self.label_camera2.setFont(font)
        self.label_camera3.setFont(font)
        self.label_camera4.setFont(font)
        self.label_camera5.setFont(font)
        self.label_location1.setFont(font)
        self.label_location2.setFont(font)
        self.label_location3.setFont(font)
        self.label_location4.setFont(font)
        self.label_location5.setFont(font)
        self.layout_color.setFont(font_color)
        self.pushButton_model.setFont(font)
        self.pushButton_start.setFont(font)
        self.pushButton_file.setFont(font)
        self.pushButton_show.setFont(font)
        self.label_status1.setText("OK")
        self.label_status2.setText("OK")
        self.label_status3.setText("OK")
        self.label_status4.setText("OK")
        self.label_status5.setText("OK")
        self.layout_color.setText("色度：")

        self.label_status1.setScaledContents(True)
        self.label_status2.setScaledContents(True)
        self.label_status3.setScaledContents(True)
        self.label_status4.setScaledContents(True)
        self.label_status5.setScaledContents(True)
        # self.label_statusc.setScaledContents(True)
        # font.setPointSize(12)
        # self.label_statusc.setFont(font)
        font.setPointSize(30)

        self.label_status1.setAutoFillBackground(True)  # 设置背景充满，为设置背景颜色的必要条件
        self.label_status2.setAutoFillBackground(True)
        self.label_status3.setAutoFillBackground(True)
        self.label_status4.setAutoFillBackground(True)
        self.label_status5.setAutoFillBackground(True)

        self.label_status1.setStyleSheet("color:green")
        self.label_status2.setStyleSheet("color:green")
        self.label_status3.setStyleSheet("color:green")
        self.label_status4.setStyleSheet("color:green")
        self.label_status5.setStyleSheet("color:green")

        self.label_status1.setFont(font)
        self.label_status2.setFont(font)
        self.label_status3.setFont(font)
        self.label_status4.setFont(font)
        self.label_status5.setFont(font)

        self.label_layout1.setFont(font)
        self.label_layout2.setFont(font)
        self.label_layout3.setFont(font)
        # self.label_layout4.setFont(font)
        # self.label_layout5.setFont(font)

        self.label_layout1.setMinimumSize(QtCore.QSize(512, 512))
        self.label_layout1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_layout2.setMinimumSize(QtCore.QSize(512, 512))
        self.label_layout2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_layout3.setMinimumSize(QtCore.QSize(512, 512))
        self.label_layout3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        # self.label_layout4.setMinimumSize(QtCore.QSize(512, 512))
        # self.label_layout4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        # self.label_layout5.setMinimumSize(QtCore.QSize(512, 512))
        # self.label_layout5.setMaximumSize(QtCore.QSize(16777215, 16777215))

        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)
        # self.gridLayout.setColumnStretch(2, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 1)
        self.label_layout1.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.label_layout2.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.label_layout3.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        # self.label_layout4.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        # self.label_layout5.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.layout_list = [self.label_layout1, self.label_layout2, self.label_layout3]
        self.status_list = [self.label_status1, self.label_status2, self.label_status3, self.label_status4,
                            self.label_status5]
        self.camera_list = [self.label_location1, self.label_location2, self.label_location3, self.label_location4,
                            self.label_location5]
        self.thread_list = [QThread(), QThread(), QThread(), QThread(), QThread()]
        self.starttime = datetime.datetime.now().strftime('%Y-%m-%d-%H-%M-%S')

        self.dialog = QtWidgets.QDialog(MainWindow)
        self.dialog.setWindowTitle(f"相机{0 + 1}检测报告")
        self.dialog.setGeometry(100, 100, 600, 1000)
        font.setPointSize(18)
        # 创建一个 QTableWidget 并放置在 QDialog 上
        self.table_widget = QtWidgets.QTableWidget(self.dialog)
        self.table_widget.setColumnCount(1)
        item = QtWidgets.QTableWidgetItem("监测信息")
        item.setFont(font)
        self.table_widget.horizontalHeader().setStyleSheet(
            "QHeaderView::section{font:18pt 'Agency FB'};")
        self.table_widget.setHorizontalHeaderItem(0, item)
        # self.table_widget.setHorizontalHeaderLabels(["ID", "缺陷种类", "缺陷置信度", "缺陷面积"])
        self.table_widget.horizontalHeader().setFont(font)
        for col in range(1):
            self.table_widget.setColumnWidth(col, 550)  # 设置每列的宽度为100像素
        # 创建一个布局并将表格小部件添加到布局中
        self.layout = QtWidgets.QVBoxLayout()
        self.layout.addWidget(self.table_widget)

        # 设置 QDialog 的布局
        self.dialog.setLayout(self.layout)
        self.dialog.show()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_start.setText(_translate("MainWindow", "开始检测"))
        self.pushButton_model.setText(_translate("MainWindow", "选择模型"))
        self.pushButton_file.setText(_translate("MainWindow", "导出表格"))
        self.pushButton_show.setText(_translate("MainWindow", "计算色度"))

        self.label_camera1.setText(_translate("MainWindow", "摄像头1(侧一)"))
        self.label_camera2.setText(_translate("MainWindow", "摄像头2(侧二)"))
        self.label_camera3.setText(_translate("MainWindow", "摄像头3(上方)"))
        self.label_camera4.setText(_translate("MainWindow", "摄像头4(待定)"))
        self.label_camera5.setText(_translate("MainWindow", "摄像头5(待定)"))

    def keyPressEvent(self, event):
        # 这里event.key（）显示的是按键的编码
        print("按下：" + str(event.key()))
        # 举例，这里Qt.Key_A注意虽然字母大写，但按键事件对大小写不敏感
        fileName = datetime.datetime.now().strftime('%Y-%m-%d-%H-%M-%S')
        if event.key() == Qt.Key_1:
            print('截取屏幕1图片，结果保存至' + str(self.result_path) + '文件夹')
            pixmap = self.label_layout1.pixmap().copy()
            if pixmap is not None:
                qImg = pixmap.toImage()
                qImg.save(self.result_path + "/" + "Screenshot" + str(fileName) + ".bmp", "BMP", 100)
            else:
                print("屏幕1未识别到图片！！")
        if event.key() == Qt.Key_2:
            print('截取屏幕2图片，结果保存至' + str(self.result_path) + '文件夹')
            pixmap = self.label_layout2.pixmap().copy()
            if pixmap is not None:
                qImg = pixmap.toImage()
                qImg.save(self.result_path + "/" + "Screenshot" + str(fileName) + ".bmp", "BMP", 100)
            else:
                print("屏幕2未识别到图片！！")
        if event.key() == Qt.Key_3:
            print('截取屏幕3图片，结果保存至' + str(self.result_path) + '文件夹')
            pixmap = self.label_layout3.pixmap().copy()
            if pixmap is not None:
                qImg = pixmap.toImage()
                qImg.save(self.result_path + "/" + "Screenshot" + str(fileName) + ".bmp", "BMP", 100)
            else:
                print("屏幕3未识别到图片！！")
        # if event.key() == Qt.Key_4:
        #     print('截取屏幕4图片，结果保存至' + str(self.result_path) + '文件夹')
        #     pixmap = self.label_layout4.pixmap().copy()
        #     if pixmap is not None:
        #         qImg = pixmap.toImage()
        #         qImg.save(self.result_path + "/" + "Screenshot" + str(fileName) + ".bmp", "BMP", 100)
        #     else:
        #         print("屏幕4未识别到图片！！")
        # if event.key() == Qt.Key_5:
        #     print('截取屏幕5图片，结果保存至' + str(self.result_path) + '文件夹')
        #     pixmap = self.label_layout5.pixmap().copy()
        #     if pixmap is not None:
        #         qImg = pixmap.toImage()
        #         qImg.save(self.result_path + "/" + "Screenshot" + str(fileName) + ".bmp", "BMP", 100)
        #     else:
        #         print("屏幕5未识别到图片！！")
        # 当需要组合键时，要很多种方式，这里举例为“shift+单个按键”，也可以采用shortcut、或者pressSequence的方法。
        if event.key() == Qt.Key_P:
            if QtWidgets.QApplication.keyboardModifiers() == Qt.ShiftModifier:
                print("shift + p打开输出文件夹")
                self.show_dir()
        if event.key() == Qt.Key_R:
            if not Globals.stop_sign:
                print("程序暂停！！！")
                Globals.stop_sign = True
            else:
                print("程序继续运行！！！")
                Globals.stop_sign = False
        if event.key() == Qt.Key_Q:
            if not Globals.visible:
                print("可视化开启！！！")
                Globals.visible = True
            else:
                print("可视化关闭！！！")
                Globals.visible = False

    def init_slots(self):
        self.pushButton_model.clicked.connect(self.select_model)
        self.pushButton_start.clicked.connect(self.camera_detect)
        self.pushButton_file.clicked.connect(self.export)
        self.pushButton_show.clicked.connect(self.show_color)
        self.check.triggered.connect(self.check_printer)
        self.color.triggered.connect(self.check_color)

    def init_logo(self):
        pix = QtGui.QPixmap('')
        # self.label_layout1.setScaledContents(True)
        # self.label_layout1.setPixmap(pix)
        Globals.sign = True

    def init_file(self):
        if not os.path.exists(self.result_path):
            os.mkdir(self.result_path)

    def load_source(self):
        self.file_path, _ = QtWidgets.QFileDialog.getOpenFileName(self, "加载数据", "data", "All Files(*)")
        self.suffix = self.file_path.split(".")[-1]  # 读取后缀
        pixmap = QPixmap(self.file_path)
        pixmap = pixmap.scaled(self.label.size(), Qt.IgnoreAspectRatio)
        self.label.setPixmap(pixmap)
        if self.file_path != "":
            self.pushButton_img.setText(self.file_path.split('/')[-1])
        # 清空result文件夹内容
        for i in os.listdir(self.result_path):
            file_data = self.result_path + "/" + i
            os.remove(file_data)

    # 选择模型
    def select_model(self):
        model_path = QtWidgets.QFileDialog.getOpenFileName(self, "选择模型", "weights", "Model files(*.pt)")
        self.model_path = model_path
        if model_path[0] != "":
            self.pushButton_model.setText(self.model_path[0].split('/')[-1])

    # 目标检测
    def target_detect(self):
        if self.check_file():
            # 点击之后防止误触，禁用按钮
            self.pushButton_img.setEnabled(False)
            self.pushButton_model.setEnabled(False)
            self.pushButton_detect.setEnabled(False)
            self.pushButton_camera_detect.setEnabled(False)
            self.thread = DetectionThread(self.file_path, self.model_path, self.label, self.tableWidget,
                                          self.status_label)
            try:
                self.thread.start()
            except Exception as e:
                print(e)
            # 子线程运行结束之后signal_done，主线程执行UI更新操作
            self.thread.signal_done.connect(self.flash_target)

    # 目标检测之前检查是否选择了数据和模型
    def check_file(self):
        if self.file_path is None or self.file_path == "":
            QMessageBox.information(self, '提示', '请先导入数据')
            return False
        if self.model_path is None or self.model_path[0] == "":
            QMessageBox.information(self, '提示', '请先选择模型')
            return False
        return True

    # 摄像头检测之前检查是否选择了模型
    def check_model(self):
        if self.model_path is None or self.model_path[0] == "":
            QMessageBox.information(self, '提示', '请先选择模型')
            return False
        return True

    # 刷新
    def flash_target(self):
        if file_is_pic(self.suffix):
            img_path = os.getcwd() + '/result/' + [f for f in os.listdir('result')][0]
            pixmap = QPixmap(img_path)
            pixmap = pixmap.scaled(self.label.size(), Qt.IgnoreAspectRatio)
            self.label.setPixmap(pixmap)
        # 刷新完之后恢复按钮状态
        self.pushButton_img.setEnabled(True)
        self.pushButton_model.setEnabled(True)
        self.pushButton_detect.setEnabled(True)
        self.pushButton_camera_detect.setEnabled(True)

    def reset_camera(self):
        self.label_layout1.setText("no camera")
        self.label_layout2.setText("no camera")
        self.label_layout3.setText("no camera")
        # self.label_layout4.setText("no camera")
        # self.label_layout5.setText("no camera")

    # 显示输出文件夹
    def show_dir(self):
        path = os.path.join(os.getcwd(), 'result')
        os.system(f"start explorer {path}")

    # 摄像头检测
    def camera_detect(self):
        if Globals.camera_running:
            Globals.camera_running = False
            self.pushButton_start.setText("开始检测")
            self.pushButton_model.setEnabled(True)
            # self.label_layout1.clear()
        else:
            if self.check_model():
                # deviceList = IMV_DeviceList()
                # interfaceType = IMV_EInterfaceType.interfaceTypeAll
                # # 枚举设备
                # nRet = MvCamera.IMV_EnumDevices(deviceList, interfaceType)
                # if IMV_OK != nRet:
                #     print("Enumeration devices failed! ErrorCode", nRet)
                #     sys.exit()
                # if deviceList.nDevNum == 0:
                #     print("find no device!")
                #     sys.exit()
                #
                # print("deviceList size is", deviceList.nDevNum)
                # displayDeviceInfo(deviceList)
                Globals.camera_running = True
                self.pushButton_model.setEnabled(False)
                self.pushButton_start.setText("停止检测")
                # for i in range(deviceList.nDevNum):
                #     self.thread_list[i] = CameraDetectionThread(self.model_path, self.layout_list[i],
                #                                                 self.status_list[i], i)
                #
                #     self.thread_list[i].start()
                #     self.thread_list[i].signal_done.connect(self.reset_camera)
                self.haikang_thread = threading.Thread(target=haikangMVCdetect.run, args=(self.layout_list,
                                                                                          self.status_list,
                                                                                          self.camera_list,
                                                                                          self.model_path[0],
                                                                                          self.table_widget)
                                                       )
                self.haikang_thread.start()

    def check_printer(self):
        os.system("C:\\Users\\Public\\Desktop\RVCManager.lnk")

    def check_color(self):
        # self.colorthread = ColorThread(self.label_statusc)
        # self.colorthread.start()
        # self.colorthread.signal_done.connect(self.reset_camera)
        os.system("C:\\Users\\31604\\Desktop\\Project\\yolov5_pyqt5-master\\seduyi\\CHNSpec.Device.Bluetooth.Demo" +
                  "\\bin\\Debug\\CHNSpec.Device.Bluetooth.Demo.exe")

    def export(self):
        if not Globals.camera_running:
            export_pdf.export(self.starttime, boxes=Globals.nums)
        else:
            Globals.export_file = [True, True, True]
            while Globals.export_file[0]:
                continue
            export_pdf.export(self.starttime, boxes=Globals.nums)

    def show_color(self):
        with open('colormsg.txt', "r") as f:
            lines = f.readlines()
            for line in lines:
                if line.startswith("光谱信息"):
                    REFDATA = line.split(',')[4:35]
                    REFDATA = [float(x) for x in REFDATA]
                    XYZ = REF2XYZ(REFDATA, None, None)
                    Lab = XYZ2LABCH(XYZ, None, None)
                    L, a, b = float(Lab[0]), float(Lab[1]), float(Lab[2])
                    print(f"L:{Lab[0]}a:{Lab[1]}b:{Lab[2]}")
                    if math.sqrt((L - 90.19) ** 2 + (a + 1.65) ** 2 + (b - 0.40) ** 2) < 5:
                        self.layout_color.setText("色度:白色")
                    elif math.sqrt((L - 81.11) ** 2 + (a - 0.09) ** 2 + (b - 4.66) ** 2) < 5:
                        self.layout_color.setText("色度:灰白色")
                    else:
                        self.layout_color.setText("色度:无法识别")


# CameraDetectionThread子线程用来执行摄像头实时检测
class CameraDetectionThread(QThread):
    signal_done = pyqtSignal(int)  # 是否结束信号

    def __init__(self, model_path, label, status_label, nDevNum):
        super(CameraDetectionThread, self).__init__()
        self.model_path = model_path
        self.label = label
        self.status_label = status_label
        self.nDevNum = nDevNum

    def run(self):
        MVCdetect.run(source=self.nDevNum, weights=self.model_path[0], show_label=self.label,
                      status_label=self.status_label,
                      use_camera=True)
        self.signal_done.emit(1)  # 发送结束信号


class ColorThread(QThread):
    signal_done = pyqtSignal(int)  # 是否结束信号

    def __init__(self, status_label):
        super(ColorThread, self).__init__()
        self.status_label = status_label

    def run(self):
        # Colordetect.run(status_label=self.status_label)

        self.signal_done.emit(1)  # 发送结束信号


class checkUi(QtWidgets.QWidget):

    def __init__(self, parent=None):
        super(checkUi, self).__init__(parent)
        self.timer_detect = QtCore.QTimer()
        self.setupUi(self)
        self.init_slots()  # 初始化槽函数
        self.file_path = None  # 数据路径
        self.model_path = None  # 模型路径
        self.file_suffix = None  # 文件后缀
        self.result_path = "result"  # 检测图片保存路径

    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(735, 552)
        self.gridLayout_2 = QtWidgets.QGridLayout(widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")

        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)

        self.pushButton_start = QtWidgets.QPushButton(widget)
        self.pushButton_start.setObjectName("pushButton_start")
        self.verticalLayout.addWidget(self.pushButton_start)
        self.pushButton_return = QtWidgets.QPushButton(widget)
        self.pushButton_return.setObjectName("pushButton_return")
        self.verticalLayout.addWidget(self.pushButton_return)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_camera2 = QtWidgets.QLabel(widget)
        self.label_camera2.setObjectName("label_camera2")
        self.gridLayout_3.addWidget(self.label_camera2, 2, 0, 1, 1)
        self.label_status3 = QtWidgets.QLabel(widget)
        self.label_status3.setText("OK")
        self.label_status3.setObjectName("label_status3")
        self.gridLayout_3.addWidget(self.label_status3, 3, 1, 1, 1)
        self.label_camera1 = QtWidgets.QLabel(widget)
        self.label_camera1.setObjectName("label_camera1")
        self.gridLayout_3.addWidget(self.label_camera1, 1, 0, 1, 1)
        self.label_camera5 = QtWidgets.QLabel(widget)
        self.label_camera5.setObjectName("label_camera5")
        self.gridLayout_3.addWidget(self.label_camera5, 5, 0, 1, 1)
        self.label_status4 = QtWidgets.QLabel(widget)
        self.label_status4.setText("OK")
        self.label_status4.setObjectName("label_status4")
        self.gridLayout_3.addWidget(self.label_status4, 4, 1, 1, 1)
        self.label_status2 = QtWidgets.QLabel(widget)
        self.label_status2.setText("OK")
        self.label_status2.setObjectName("label_status2")
        self.gridLayout_3.addWidget(self.label_status2, 2, 1, 1, 1)
        self.label_status1 = QtWidgets.QLabel(widget)
        self.label_status1.setText("OK")
        self.label_status1.setObjectName("label_status1")
        self.gridLayout_3.addWidget(self.label_status1, 1, 1, 1, 1)
        self.label_camera4 = QtWidgets.QLabel(widget)
        self.label_camera4.setObjectName("label_camera4")
        self.gridLayout_3.addWidget(self.label_camera4, 4, 0, 1, 1)
        self.label_camera3 = QtWidgets.QLabel(widget)
        self.label_camera3.setObjectName("label_camera3")
        self.gridLayout_3.addWidget(self.label_camera3, 3, 0, 1, 1)
        self.label_status5 = QtWidgets.QLabel(widget)
        self.label_status5.setText("OK")
        self.label_status5.setObjectName("label_status5")
        self.gridLayout_3.addWidget(self.label_status5, 5, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.label_layout3 = QtWidgets.QLabel(widget)
        self.label_layout3.setText("no camera")
        self.label_layout3.setObjectName("label_layout3")
        self.gridLayout.addWidget(self.label_layout3, 1, 0, 1, 1)
        self.label_layout5 = QtWidgets.QLabel(widget)
        self.label_layout5.setText("no camera")
        self.label_layout5.setObjectName("label_layout5")
        self.gridLayout.addWidget(self.label_layout5, 1, 2, 1, 1)
        self.label_layout1 = QtWidgets.QLabel(widget)
        self.label_layout1.setText("no camera")
        self.label_layout1.setObjectName("label_layout1")
        self.gridLayout.addWidget(self.label_layout1, 0, 1, 1, 1)
        self.label_layout4 = QtWidgets.QLabel(widget)
        self.label_layout4.setText("no camera")
        self.label_layout4.setObjectName("label_layout4")
        self.gridLayout.addWidget(self.label_layout4, 1, 1, 1, 1)
        self.label_layout2 = QtWidgets.QLabel(widget)
        self.label_layout2.setText("no camera")
        self.label_layout2.setObjectName("label_layout2")
        self.gridLayout.addWidget(self.label_layout2, 0, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.pushButton_start.setFont(font)
        self.pushButton_return.setFont(font)

        self.label_camera1.setFont(font)
        self.label_camera2.setFont(font)
        self.label_camera3.setFont(font)
        self.label_camera4.setFont(font)
        self.label_camera5.setFont(font)
        font.setPointSize(30)
        self.label_layout1.setFont(font)
        self.label_layout2.setFont(font)
        self.label_layout3.setFont(font)
        self.label_layout4.setFont(font)
        self.label_layout5.setFont(font)

        self.label_status1.setFont(font)
        self.label_status2.setFont(font)
        self.label_status3.setFont(font)
        self.label_status4.setFont(font)
        self.label_status5.setFont(font)

        self.label_layout1.setStyleSheet("background-color: black")
        self.label_layout2.setStyleSheet("background-color: black")
        self.label_layout3.setStyleSheet("background-color: black")
        self.label_layout4.setStyleSheet("background-color: black")
        self.label_layout5.setStyleSheet("background-color: black")

        self.label_layout1.setMinimumSize(QtCore.QSize(512, 512))
        self.label_layout1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_layout2.setMinimumSize(QtCore.QSize(512, 512))
        self.label_layout2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_layout3.setMinimumSize(QtCore.QSize(512, 512))
        self.label_layout3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_layout4.setMinimumSize(QtCore.QSize(512, 512))
        self.label_layout4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_layout5.setMinimumSize(QtCore.QSize(512, 512))
        self.label_layout5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_layout1.setScaledContents(True)
        self.label_layout2.setScaledContents(True)
        self.label_layout3.setScaledContents(True)
        self.label_layout4.setScaledContents(True)
        self.label_layout5.setScaledContents(True)

        self.label_layout1.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.label_layout2.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.label_layout3.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.label_layout4.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.label_layout5.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)

        self.label_status1.setAutoFillBackground(True)  # 设置背景充满，为设置背景颜色的必要条件
        self.label_status2.setAutoFillBackground(True)
        self.label_status3.setAutoFillBackground(True)
        self.label_status4.setAutoFillBackground(True)
        self.label_status5.setAutoFillBackground(True)

        self.label_status1.setStyleSheet("color:green")
        self.label_status2.setStyleSheet("color:green")
        self.label_status3.setStyleSheet("color:green")
        self.label_status4.setStyleSheet("color:green")
        self.label_status5.setStyleSheet("color:green")

        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 1)

        self.layout_list = [self.label_layout1, self.label_layout2, self.label_layout3, self.label_layout4,
                            self.label_layout5]
        self.status_list = [self.label_status1, self.label_status2, self.label_status3, self.label_status4,
                            self.label_status5]
        self.thread_list = [QThread(), QThread(), QThread(), QThread(),
                            QThread()]
        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def init_slots(self):
        self.pushButton_return.clicked.connect(self.multi_camera)
        self.pushButton_start.clicked.connect(self.camera_detect)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "Form"))
        self.pushButton_start.setText(_translate("widget", "开始检测"))
        self.pushButton_return.setText(_translate("widget", "返回"))
        self.label_camera2.setText(_translate("widget", "摄像头2"))
        self.label_camera1.setText(_translate("widget", "摄像头1"))
        self.label_camera5.setText(_translate("widget", "摄像头5"))
        self.label_camera4.setText(_translate("widget", "摄像头4"))
        self.label_camera3.setText(_translate("widget", "摄像头3"))

    def resizeEvent(self, event):
        super().resizeEvent(event)

    def reset_camera(self):
        self.label_layout1.setText("no camera")
        self.label_layout2.setText("no camera")
        self.label_layout3.setText("no camera")
        self.label_layout4.setText("no camera")
        self.label_layout5.setText("no camera")

    # 摄像头检测
    def camera_detect(self):
        if Globals.camera_running:
            Globals.camera_running = False
            self.pushButton_start.setText("开始检测")
            self.pushButton_return.setEnabled(True)
            self.label_layout1.clear()
        else:
            Globals.camera_running = True
            # deviceList = IMV_DeviceList()
            # interfaceType = IMV_EInterfaceType.interfaceTypeAll
            # # 枚举设备
            # nRet = MvCamera.IMV_EnumDevices(deviceList, interfaceType)
            # if IMV_OK != nRet:
            #     print("Enumeration devices failed! ErrorCode", nRet)
            #     sys.exit()
            # if deviceList.nDevNum == 0:
            #     print("find no device!")
            #     sys.exit()
            #
            # print("deviceList size is", deviceList.nDevNum)
            # displayDeviceInfo(deviceList)
            self.pushButton_return.setEnabled(False)
            self.pushButton_start.setText("停止检测")
            # for i in range(deviceList.nDevNum):
            #     self.thread_list[i] = CheckThread(self.layout_list[i],
            #                                       self.status_list[i], i)
            #     self.thread_list[i].start()
            #     self.thread_list[i].signal_done.connect(self.reset_camera)
            self.haikang_thread = threading.Thread(target=haikangdetect.run, args=self.layout_list)
            self.haikang_thread.start()
            # for i in range(deviceList.nDevNum):
            #     self.thread_list[i] = CheckThread(self.layout_list[i], i)
            #     self.thread_list[i].start()
            #     self.thread_list[i].signal_done.connect(self.reset_camera)

    def multi_camera(self):
        self.hide()
        self.camera_ui = cameraUI()
        self.camera_ui.show()

    def keyPressEvent(self, event):
        # 这里event.key（）显示的是按键的编码
        print("按下：" + str(event.key()))
        # 举例，这里Qt.Key_A注意虽然字母大写，但按键事件对大小写不敏感
        fileName = datetime.datetime.now().strftime('%Y-%m-%d-%H-%M-%S')
        if event.key() == Qt.Key_1:
            print('截取屏幕1图片，结果保存至' + str(self.result_path) + '文件夹')
            pixmap = self.label_layout1.pixmap().copy()
            if pixmap is not None:
                qImg = pixmap.toImage()
                qImg.save(self.result_path + "/" + "Screenshot" + str(fileName) + ".bmp", "BMP", 100)
            else:
                print("屏幕1未识别到图片！！")
        if event.key() == Qt.Key_2:
            print('截取屏幕2图片，结果保存至' + str(self.result_path) + '文件夹')
            pixmap = self.label_layout2.pixmap().copy()
            if pixmap is not None:
                qImg.save(self.result_path + "/" + str(datetime.datetime.now()).strip() + ".jpg", Qt.Q_NULLPTR, 100)
            else:
                print("屏幕1未识别到图片！！")
        if event.key() == Qt.Key_3:
            print('截取屏幕3图片，结果保存至' + str(self.result_path) + '文件夹')
            pixmap = self.label_layout3.pixmap().copy()
            if pixmap is not None:
                qImg = pixmap.toImage()
                qImg.save(self.result_path + "/" + str(datetime.datetime.now()).strip() + ".jpg", Qt.Q_NULLPTR, 100)
            else:
                print("屏幕1未识别到图片！！")
        if event.key() == Qt.Key_4:
            print('截取屏幕4图片，结果保存至' + str(self.result_path) + '文件夹')
            pixmap = self.label_layout4.pixmap().copy()
            if pixmap is not None:
                qImg = pixmap.toImage()
                qImg.save(self.result_path + "/" + str(datetime.datetime.now()).strip() + ".jpg", Qt.Q_NULLPTR, 100)
            else:
                print("屏幕1未识别到图片！！")
        if event.key() == Qt.Key_5:
            print('截取屏幕5图片，结果保存至' + str(self.result_path) + '文件夹')
            pixmap = self.label_layout5.pixmap().copy()
            if pixmap is not None:
                qImg = pixmap.toImage()
                qImg.save(self.result_path + "/" + str(datetime.datetime.now()), Qt.Q_NULLPTR, 100)
            else:
                print("屏幕1未识别到图片！！")
        # 当需要组合键时，要很多种方式，这里举例为“shift+单个按键”，也可以采用shortcut、或者pressSequence的方法。
        if event.key() == Qt.Key_P:
            if QtWidgets.QApplication.keyboardModifiers() == Qt.ShiftModifier:
                print("shift + p打开输出文件夹")
                self.show_dir()


class CheckThread(QThread):
    signal_done = pyqtSignal(int)  # 是否结束信号

    def __init__(self, label, nDevNum):
        super(CheckThread, self).__init__()
        self.label = label
        self.nDevNum = nDevNum

    def run(self):
        checkdetect.run(source=self.nDevNum, show_label=self.label,
                        use_camera=True)
        self.signal_done.emit(1)  # 发送结束信号
