# -*- coding: utf-8 -*-
import sys

import qdarkstyle
# Form implementation generated from reading ui file 'widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Report_UI(QtWidgets.QMainWindow):
    def __init__(self, parent=None, index=0):
        super(Report_UI, self).__init__(parent)
        self.setupUi(self, index)

    def setupUi(self, MainWindow, index):
        font = QtGui.QFont()
        font.setPointSize(16)
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 1000)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.tablewidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tablewidget.setObjectName("listWidget")
        self.tablewidget.setColumnCount(4)  # 设置列数
        # 设置每一列的宽度相同
        for col in range(4):
            self.tablewidget.setColumnWidth(col, 200)  # 设置每列的宽度为100像素
        # 设置列名
        self.tablewidget.setHorizontalHeaderLabels(["ID", "缺陷种类", "缺陷置信度", "缺陷面积"])
        header = self.tablewidget.horizontalHeader()
        header.setFont(font)
        self.gridLayout.addWidget(self.tablewidget, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 754, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow, index)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow, index):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", f"相机{index + 1}缺陷报告"))


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    # app.setStyleSheet(qdarkstyle.load_stylesheet_pyqt5())
    ui = Report_UI(index=1)
    # 设置窗口图标
    ui.show()
    sys.exit(app.exec_())
