# -*- coding: utf-8 -*-
import os

# Form implementation generated from reading ui file 'yolov8.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import detect
import MVCdetect
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt, QThread, pyqtSignal
from PyQt5.QtGui import QPixmap
from PyQt5.QtWidgets import QMessageBox

from utils.myutil import file_is_pic, Globals


class Ui_MainWindow(QtWidgets.QMainWindow):
    def __init__(self, parent=None):
        super(Ui_MainWindow, self).__init__(parent)
        self.timer_detect = QtCore.QTimer()
        self.setupUi(self)
        self.init_logo()  # 初始化logo
        self.init_slots()  # 初始化槽函数
        self.file_path = None  # 数据路径
        self.model_path = None  # 模型路径
        self.file_suffix = None  # 文件后缀
        self.result_path = "result"  # 检测图片保存路径
        self.init_file()  # 初始化必要的文件夹

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(856, 657)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        MainWindow.setPalette(palette)
        MainWindow.setTabletTracking(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_detect = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_detect.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.pushButton_detect.setFont(font)
        self.pushButton_detect.setMouseTracking(True)
        self.pushButton_detect.setObjectName("pushButton_detect")
        self.gridLayout.addWidget(self.pushButton_detect, 1, 0, 1, 1)
        self.pushButton_img = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_img.setMinimumSize(QtCore.QSize(0, 50))

        self.pushButton_img.setFont(font)
        self.pushButton_img.setMouseTracking(True)
        self.pushButton_img.setObjectName("pushButton_img")
        self.gridLayout.addWidget(self.pushButton_img, 0, 0, 1, 1)
        self.pushButton_model = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_model.setMinimumSize(QtCore.QSize(0, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.pushButton_model.setPalette(palette)

        self.pushButton_model.setFont(font)
        self.pushButton_model.setMouseTracking(True)
        self.pushButton_model.setObjectName("pushButton_model")
        self.gridLayout.addWidget(self.pushButton_model, 0, 1, 1, 1)
        self.pushButton_camera_detect = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_camera_detect.setMinimumSize(QtCore.QSize(0, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        self.pushButton_camera_detect.setPalette(palette)

        self.pushButton_camera_detect.setFont(font)
        self.pushButton_camera_detect.setMouseTracking(True)
        self.pushButton_camera_detect.setObjectName("pushButton_camera_detect")
        self.gridLayout.addWidget(self.pushButton_camera_detect, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("border: 1px solid black;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label.setMinimumSize(QtCore.QSize(512, 512))
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label.setScaledContents(True)
        self.verticalLayout_2.addWidget(self.label)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 1, 2, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_showdir = QtWidgets.QPushButton(self.centralwidget)

        self.pushButton_showdir.setFont(font)
        self.pushButton_showdir.setMouseTracking(True)
        self.pushButton_showdir.setObjectName("pushButton_showdir")
        self.verticalLayout.addWidget(self.pushButton_showdir)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.tableWidget.setStyleSheet("QTableWidget::item::selected\n"
                                       "{\n"
                                       "    background:green;\n"
                                       "}\n"
                                       "")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem("检测记录")
        item.setFont(font)
        self.tableWidget.horizontalHeader().setStyleSheet(
            "QHeaderView::section{font:14pt 'Agency FB'};")

        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(300)
        self.tableWidget.setFont(font)
        self.verticalLayout.addWidget(self.tableWidget)
        self.gridLayout_3.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.status_label = QtWidgets.QLabel(self.centralwidget)
        self.status_label.setText("")
        self.status_label.setObjectName("detect_label")
        self.status_label.setMinimumSize(QtCore.QSize(120, 120))
        self.status_label.setMaximumSize(QtCore.QSize(120, 120))
        self.status_label.setScaledContents(True)
        font.setPointSize(60)
        self.status_label.setFont(font)
        self.status_label.setAutoFillBackground(True)  # 设置背景充满，为设置背景颜色的必要条件
        self.status_label.setStyleSheet("color:green")

        self.gridLayout_3.addWidget(self.status_label, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 856, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setAutoFillBackground(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.dialog = QtWidgets.QDialog(MainWindow)
        self.dialog.setWindowTitle(f"相机{0 + 1}检测报告")
        self.dialog.setGeometry(100, 100, 600, 1000)
        font.setPointSize(18)
        # 创建一个 QTableWidget 并放置在 QDialog 上
        self.table_widget = QtWidgets.QTableWidget(self.dialog)
        self.table_widget.setColumnCount(1)
        item = QtWidgets.QTableWidgetItem("监测信息")
        item.setFont(font)
        self.table_widget.horizontalHeader().setStyleSheet(
            "QHeaderView::section{font:18pt 'Agency FB'};")
        self.table_widget.setHorizontalHeaderItem(0, item)
        # self.table_widget.setHorizontalHeaderLabels(["ID", "缺陷种类", "缺陷置信度", "缺陷面积"])
        self.table_widget.horizontalHeader().setFont(font)
        for col in range(1):
            self.table_widget.setColumnWidth(col, 550)  # 设置每列的宽度为100像素
        # 创建一个布局并将表格小部件添加到布局中
        self.layout = QtWidgets.QVBoxLayout()
        self.layout.addWidget(self.table_widget)

        # 设置 QDialog 的布局
        self.dialog.setLayout(self.layout)
        self.dialog.show()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "yolov8检测缺陷demo"))
        self.pushButton_detect.setText(_translate("MainWindow", "图片检测"))
        self.pushButton_img.setText(_translate("MainWindow", "加载图片"))
        self.pushButton_model.setText(_translate("MainWindow", "加载模型"))
        self.pushButton_camera_detect.setText(_translate("MainWindow", "视频流检测"))
        self.pushButton_showdir.setText(_translate("MainWindow", "查看导出文件夹"))
        self.menu.setTitle(_translate("MainWindow", "菜单"))

    def init_slots(self):
        self.pushButton_img.clicked.connect(self.load_source)
        self.pushButton_model.clicked.connect(self.select_model)
        self.pushButton_detect.clicked.connect(self.target_detect)
        self.pushButton_showdir.clicked.connect(self.show_dir)
        self.pushButton_camera_detect.clicked.connect(self.camera_detect)

    def init_logo(self):
        pix = QtGui.QPixmap('')
        self.label.setScaledContents(True)
        self.label.setPixmap(pix)

    def init_file(self):
        if not os.path.exists(self.result_path):
            os.mkdir(self.result_path)

    def load_source(self):
        self.file_path, _ = QtWidgets.QFileDialog.getOpenFileName(self, "加载数据", r"C:\Users\31604\Desktop\fujidata\12mm\JPEGImages", "All Files(*)")
        self.suffix = self.file_path.split(".")[-1]  # 读取后缀
        pixmap = QPixmap(self.file_path)
        pixmap = pixmap.scaled(self.label.size(), Qt.IgnoreAspectRatio)
        self.label.setPixmap(pixmap)
        if self.file_path != "":
            self.pushButton_img.setText(self.file_path.split('/')[-1])
        # 清空result文件夹内容
        for i in os.listdir(self.result_path):
            file_data = self.result_path + "/" + i
            os.remove(file_data)
        RC = self.tableWidget.rowCount()
        for i in range(RC):
            self.tableWidget.removeRow(0)

    # 选择模型
    def select_model(self):
        model_path = QtWidgets.QFileDialog.getOpenFileName(self, "选择模型", "weights", "Model files(*.pt)")
        self.model_path = model_path
        if model_path[0] != "":
            self.pushButton_model.setText(self.model_path[0].split('/')[-1])

    # 目标检测
    def target_detect(self):
        if self.check_file():
            # 点击之后防止误触，禁用按钮
            self.pushButton_img.setEnabled(False)
            self.pushButton_model.setEnabled(False)
            self.pushButton_detect.setEnabled(False)
            self.pushButton_camera_detect.setEnabled(False)
            self.thread = DetectionThread(self.file_path, self.model_path, self.label, self.tableWidget,
                                          self.status_label, self.table_widget)
            self.thread.start()
            # 子线程运行结束之后signal_done，主线程执行UI更新操作
            self.thread.signal_done.connect(self.flash_target)

    # 目标检测之前检查是否选择了数据和模型
    def check_file(self):
        if self.file_path is None or self.file_path == "":
            QMessageBox.information(self, '提示', '请先导入数据')
            return False
        if self.model_path is None or self.model_path[0] == "":
            QMessageBox.information(self, '提示', '请先选择模型')
            return False
        return True

    # 摄像头检测之前检查是否选择了模型
    def check_model(self):
        if self.model_path is None or self.model_path[0] == "":
            QMessageBox.information(self, '提示', '请先选择模型')
            return False
        return True

    # 刷新
    def flash_target(self):
        if file_is_pic(self.suffix):
            img_path = os.getcwd() + '/result/' + [f for f in os.listdir('result')][0]
            pixmap = QPixmap(img_path)
            pixmap = pixmap.scaled(self.label.size(), Qt.IgnoreAspectRatio)
            self.label.setPixmap(pixmap)
        # 刷新完之后恢复按钮状态
        self.pushButton_img.setEnabled(True)
        self.pushButton_model.setEnabled(True)
        self.pushButton_detect.setEnabled(True)
        self.pushButton_camera_detect.setEnabled(True)

    # 显示输出文件夹
    def show_dir(self):
        path = os.path.join(os.getcwd(), 'result')
        os.system(f"start explorer {path}")

    # 摄像头检测
    def camera_detect(self):
        RC = self.tableWidget.rowCount()
        for i in range(RC):
            self.tableWidget.removeRow(0)
        if Globals.camera_running:
            Globals.camera_running = False
            self.pushButton_camera_detect.setText("摄像头检测")
            self.pushButton_img.setEnabled(True)
            self.pushButton_model.setEnabled(True)
            self.pushButton_detect.setEnabled(True)
            self.label.clear()
        else:
            if self.check_model():
                Globals.camera_running = True
                self.pushButton_img.setEnabled(False)
                self.pushButton_model.setEnabled(False)
                self.pushButton_detect.setEnabled(False)
                self.pushButton_camera_detect.setText("关闭摄像头")
                self.camera_thread = CameraDetectionThread(self.model_path, self.label, self.tableWidget,
                                                           self.status_label)
                self.camera_thread.start()


# DetectionThread子线程用来执行导入资源的目标检测
class DetectionThread(QThread):
    signal_done = pyqtSignal(int)  # 是否结束信号

    def __init__(self, file_path, model_path, label, table, status_label, table_widget):
        super(DetectionThread, self).__init__()
        self.file_path = file_path
        self.model_path = model_path
        self.label = label
        self.table = table
        self.status_label = status_label
        self.table_widget = table_widget

    def run(self):
        detect.run(source=self.file_path, weights=self.model_path[0], show_label=self.label,
                   status_label=self.status_label, table=self.table_widget, save_img=True)
        self.signal_done.emit(1)  # 发送结束信号


# CameraDetectionThread子线程用来执行摄像头实时检测
class CameraDetectionThread(QThread):
    def __init__(self, model_path, label, table, status_label):
        super(CameraDetectionThread, self).__init__()
        self.model_path = model_path
        self.label = label
        self.table = table
        self.status_label = status_label

    def run(self):
        # self.label.setFixedSize(2560, 1440)
        MVCdetect.run(source=0, weights=self.model_path[0], show_label=self.label, status_label=self.status_label,
                      table_widget=self.table, save_img=False, use_camera=True)
